# Generated by Django 5.2.9 on 2025-12-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this secret", max_length=255
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("azure", "Azure"),
                            ("unifi", "UniFi"),
                            ("synology", "Synology"),
                            ("generic", "Generic"),
                        ],
                        db_index=True,
                        help_text="Service type: azure, unifi, synology, or generic",
                        max_length=50,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Secret key (e.g., 'azure_client_secret', 'unifi_password')",
                        max_length=255,
                    ),
                ),
                ("encrypted_value", models.TextField(help_text="Encrypted secret value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "secrets",
                "ordering": ["service_type", "name"],
                "unique_together": {("service_type", "key")},
            },
        ),
    ]
