#!/bin/bash
#
# setup_n8n_node.sh - Install and configure n8n on a worker node
#
# Usage:
#   ./setup_n8n_node.sh <N8N_USER> <N8N_PASSWORD> <N8N_ENCRYPTION_KEY>
#
# This script:
#   1. Updates system packages
#   2. Installs Docker + Docker Compose plugin
#   3. Creates n8n directories
#   4. Writes docker-compose.yml and .env files
#   5. Starts n8n container
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check arguments
if [ $# -lt 3 ]; then
    echo "Usage: $0 <N8N_USER> <N8N_PASSWORD> <N8N_ENCRYPTION_KEY>"
    echo ""
    echo "Arguments:"
    echo "  N8N_USER           - Basic auth username for n8n web UI"
    echo "  N8N_PASSWORD       - Basic auth password for n8n web UI"
    echo "  N8N_ENCRYPTION_KEY - 32-byte hex key for encrypting credentials"
    exit 1
fi

N8N_USER="$1"
N8N_PASSWORD="$2"
N8N_ENCRYPTION_KEY="$3"

# Get the host IP for n8n configuration
HOST_IP=$(hostname -I | awk '{print $1}')

log_info "Starting n8n installation on $(hostname) ($HOST_IP)"

# ============================================================================
# Step 1: Update system packages
# ============================================================================
log_info "Step 1/5: Updating system packages..."
sudo apt-get update -qq
sudo apt-get upgrade -y -qq

# ============================================================================
# Step 2: Install Docker + Docker Compose
# ============================================================================
log_info "Step 2/5: Installing Docker..."

if command -v docker &> /dev/null; then
    log_info "Docker already installed: $(docker --version)"
else
    # Install Docker using official script
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sudo sh /tmp/get-docker.sh
    rm /tmp/get-docker.sh
    
    # Add current user to docker group
    sudo usermod -aG docker $USER
    log_info "Docker installed: $(docker --version)"
fi

# Ensure Docker Compose plugin is available
if docker compose version &> /dev/null; then
    log_info "Docker Compose plugin available: $(docker compose version)"
else
    log_info "Installing Docker Compose plugin..."
    sudo apt-get install -y -qq docker-compose-plugin
fi

# Start Docker service
sudo systemctl enable docker
sudo systemctl start docker

# ============================================================================
# Step 3: Create n8n directories
# ============================================================================
log_info "Step 3/5: Creating n8n directories..."

sudo mkdir -p /opt/n8n/data
sudo mkdir -p /opt/n8n/backups

# Set ownership to current user (usually jexida)
sudo chown -R $USER:$USER /opt/n8n

# ============================================================================
# Step 4: Create configuration files
# ============================================================================
log_info "Step 4/5: Creating configuration files..."

# Create .env file
cat > /opt/n8n/.env << EOF
# n8n Environment Configuration
# Generated by setup_n8n_node.sh on $(date)

N8N_USER=${N8N_USER}
N8N_PASSWORD=${N8N_PASSWORD}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
EOF

chmod 600 /opt/n8n/.env
log_info "Created /opt/n8n/.env"

# Create docker-compose.yml
cat > /opt/n8n/docker-compose.yml << EOF
version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=\${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=\${N8N_PASSWORD}
      - N8N_HOST=${HOST_IP}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=\${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
    volumes:
      - /opt/n8n/data:/home/node/.n8n
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF

log_info "Created /opt/n8n/docker-compose.yml"

# ============================================================================
# Step 5: Start n8n container
# ============================================================================
log_info "Step 5/5: Starting n8n container..."

cd /opt/n8n

# Pull latest image
docker compose pull

# Start container
docker compose up -d

# Wait for container to be healthy
log_info "Waiting for n8n to become healthy..."
sleep 10

# Check container status
if docker compose ps | grep -q "running"; then
    log_info "n8n container is running!"
else
    log_error "n8n container failed to start. Check logs with: docker compose logs"
    exit 1
fi

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "=============================================="
echo -e "${GREEN}n8n Installation Complete!${NC}"
echo "=============================================="
echo ""
echo "Access n8n at: http://${HOST_IP}:5678"
echo "Username: ${N8N_USER}"
echo "Password: <configured>"
echo ""
echo "Useful commands:"
echo "  cd /opt/n8n"
echo "  docker compose logs -f     # View logs"
echo "  docker compose restart     # Restart n8n"
echo "  docker compose down        # Stop n8n"
echo "  docker compose up -d       # Start n8n"
echo ""
echo "Data directory: /opt/n8n/data"
echo "Backups directory: /opt/n8n/backups"
echo ""

